// Generate the host Typert face and the client remote types from one method list.
// ctx.typert accepts TYPERT.face === 'host' plus a documented model and strict codecs.
import { writeFileSync } from 'node:fs'

const pkg = 'dsh-plugin-herdr'
const methods = [
  ['status', 'status(request?: unknown): Promise<unknown>', true, false],
  ['dashboard', 'dashboard(): Promise<unknown>', false, false],
  ['topology', 'topology(): Promise<unknown>', false, false],
  ['agentOutputs', 'agentOutputs(request: unknown): Promise<unknown>', true, false],
  ['sessionPane', 'sessionPane(request: unknown): Promise<unknown>', true, false],
  ['paneSession', 'paneSession(request: unknown): Promise<unknown>', true, false],
  ['start', 'start(): Promise<unknown>', false, false],
  ['close', 'close(request: unknown): Promise<unknown>', true, false],
  ['rename', 'rename(request: unknown): Promise<unknown>', true, false],
  ['paneInput', 'paneInput(request: unknown): Promise<unknown>', true, false],
  ['terminalBootstrap', 'terminalBootstrap(request: unknown): Promise<unknown>', true, false],
  ['terminalStart', 'terminalStart(request: unknown): Promise<unknown>', true, false],
  ['terminalCommand', 'terminalCommand(request: unknown): Promise<unknown>', true, false],
  ['terminalRelease', 'terminalRelease(request: unknown): Promise<unknown>', true, false],
  ['terminalStats', 'terminalStats(): Promise<unknown>', false, false],
  ['events', 'events(request?: unknown, signal?: AbortSignal): AsyncIterable<unknown>', true, true],
]

const lazy = name => `let ${name}$value\nconst ${name} = () => (${name}$value ??= z.unknown())`
const schemas = methods.flatMap(([name, , hasArgs]) => {
  const out = [lazy(`${name}Result`)]
  if (hasArgs) out.unshift(lazy(`${name}Request`))
  return out
})

function invocation(name, _signature, hasArgs, stream) {
  const id = `${pkg}#herdr/${name}`
  const parameters = hasArgs
    ? `[{
        name: 'request',
        wire: 'request',
        source: 'json',
        codec: {
          mode: 'strict',
          typeSymbol: '${pkg}#${name}:request',
          create: ${name}Request,
        },
      }]`
    : '[]'
  return `{
      id: '${id}',
      service: 'herdrPanel',
      namespace: 'herdr',
      method: '${name}',${stream ? "\n      mode: 'stream'," : ''}
      invocation: { kind: 'direct' },
      parameters: ${parameters},${stream ? "\n      cancellation: { parameter: 'signal' }," : ''}
      result: {
        mode: 'strict',
        typeSymbol: '${pkg}#${name}:result',
        create: ${name}Result,
      },
      sourceLocation: { file: 'src/panel/remote.ts', line: 1, column: 1 },
    }`
}

const members = methods.map(([name, signature]) => `        {
          kind: 'method',
          name: '${name}',
          signature: '${signature.replaceAll("'", "\\'")}',
          summary: '${name}',
          jsDoc: '/** ${name} */',
        }`).join(',\n')

const host = `/* Generated by scripts/gen-typert.mjs — do not edit. */
import { z } from 'zod'

${schemas.join('\n')}

export const TYPERT = {
  package: '${pkg}',
  face: 'host',
  schemas: [],
  invocations: [
    ${methods.map(method => invocation(...method)).join(',\n    ')},
  ],
  model: {
    services: [{
      description: 'Herdr control plane and Web panel service.',
      summary: 'Herdr control plane and Web panel service.',
      tags: [],
      jsDoc: '/** Herdr control plane and Web panel service. */',
      key: 'herdrPanel',
      exportName: 'HerdrPanelService',
      members: [
${members}
      ],
      types: [],
    }],
    events: [],
    objects: [],
  },
}

export default TYPERT
`

const clientFace = methods.map(([name, signature]) => {
  const params = signature.includes('request?:')
    ? 'request?: unknown'
    : signature.includes('request:')
      ? 'request: unknown'
      : ''
  const result = signature.includes('AsyncIterable') ? 'AsyncIterable<unknown>' : 'Promise<unknown>'
  return `  ${name}(${params}): ${result}`
}).join('\n')

const client = `/* Generated by scripts/gen-typert.mjs — do not edit. */
export interface HerdrRemote {
${clientFace}
}
`

const dts = `/* Generated by scripts/gen-typert.mjs — do not edit. */
export interface TypertInvocation {
  id: string
  service: string
  namespace: string
  method: string
  mode?: 'stream'
  cancellation?: { parameter: string }
  parameters: unknown[]
  result: { mode: string; typeSymbol: string; create: () => { parse: (value: unknown) => any } }
}
export interface TypertManifest {
  package: string
  face: 'host'
  schemas: unknown[]
  invocations: TypertInvocation[]
  model: unknown
}
export declare const TYPERT: TypertManifest
export default TYPERT
`

writeFileSync('lib/typert.host.js', host)
writeFileSync('lib/typert.host.d.ts', dts)
writeFileSync('src/web/herdr-remote.d.ts', client)
console.log('typert artifacts written')
