/* Generated by scripts/gen-typert.mjs — do not edit. */
export interface HerdrRemote {
  status(request?: unknown): Promise<unknown>
  dashboard(): Promise<unknown>
  topology(): Promise<unknown>
  agentOutputs(request: unknown): Promise<unknown>
  sessionPane(request: unknown): Promise<unknown>
  paneSession(request: unknown): Promise<unknown>
  start(): Promise<unknown>
  close(request: unknown): Promise<unknown>
  rename(request: unknown): Promise<unknown>
  paneInput(request: unknown): Promise<unknown>
  terminalBootstrap(request: unknown): Promise<unknown>
  terminalStart(request: unknown): Promise<unknown>
  terminalCommand(request: unknown): Promise<unknown>
  terminalRelease(request: unknown): Promise<unknown>
  terminalStats(): Promise<unknown>
  events(request?: unknown): AsyncIterable<unknown>
}
